# Generated by Django 5.1.4 on 2025-01-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('sprite', models.URLField()),
                ('types', models.CharField(max_length=100)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('special_attack', models.IntegerField()),
                ('special_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('cry_url', models.URLField()),
                ('moves', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('evolutions', models.TextField(blank=True, max_length=255, null=True)),
                ('abilities', models.TextField(default='')),
                ('base_experience', models.IntegerField(default=0)),
                ('capture_rate', models.IntegerField(default=0)),
                ('habitat', models.CharField(default='Unknown', max_length=100)),
                ('forms', models.TextField(default='')),
            ],
        ),
    ]
