# Generated by Django 5.1.4 on 2025-01-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='animated_back_sprite',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='animated_front_sprite',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='cromatique_sprite',
            field=models.URLField(blank=True, null=True),
        ),
    ]
