# Generated by Django 5.1.4 on 2025-01-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_rename_cromatique_sprite_pokemon_chromatique_sprite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('fling_power', models.IntegerField()),
                ('fling_effect', models.CharField(max_length=100)),
                ('attributes', models.TextField(default='')),
                ('category', models.CharField(max_length=100)),
                ('effect_entries', models.TextField(default='')),
                ('flavor_text_entries', models.TextField(default='')),
                ('game_indices', models.TextField(default='')),
                ('names', models.TextField(default='')),
                ('sprites', models.TextField(default='')),
                ('held_by_pokemon', models.TextField(default='')),
                ('baby_trigger_for', models.TextField(default='')),
                ('machines', models.TextField(default='')),
            ],
        ),
    ]
