# Generated by Django 5.1.4 on 2025-01-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='attributes',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='item',
            name='baby_trigger_for',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='item',
            name='effect_entries',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='item',
            name='flavor_text_entries',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='item',
            name='fling_effect',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='fling_power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='game_indices',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='item',
            name='held_by_pokemon',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='item',
            name='machines',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='item',
            name='names',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='item',
            name='sprites',
            field=models.JSONField(default=dict),
        ),
    ]
