### Test the login endpoint
POST http://localhost:8000/api/login/
Content-Type: application/json

{
    "username": "newuser",
    "password": "newpassword"
}

### Test the registration endpoint
POST http://localhost:8000/api/register/
Content-Type: application/json

{
    "username": "newuser",
    "password": "newpassword",
    "email": "newuser@example.com"
}

### Test the token endpoint
GET http://localhost:8000/api/test_token/
Content-Type: application/json
Authorization: Token 76762d9bf0231a0e6ad7fad4d7e9ccbe91f981c7

### Test the user/profile endpoint
GET http://localhost:8000/api/user/profile/
Content-Type: application/json
Authorization: Token 76762d9bf0231a0e6ad7fad4d7e9ccbe91f981c7